server:
  port: 9999

spring:
#  profiles:
#    active: dev
  datasource:
    #    url: jdbc:h2:mem:test;MODE=PostgreSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/algo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 12345
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none # disable DB schema creation from entity

  flyway:
    enabled: false
    baseline-on-migrate: true





#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#  sql:
#    init:
#      schema-locations: sql/schema.sql
#      data-locations: sql/data.sql

