server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  flyway:
    baseline-on-migrate: true



