server:
  port: 9999

spring:
  profiles:
    active: dev

#  datasource:
##    url: jdbc:h2:mem:test;MODE=PostgreSQL
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
#
#  flyway:
#    baseline-on-migrate: true




