server:
  port: 9999

spring:
  profiles:
    active: dev
  datasource:
    #    url: jdbc:h2:mem:test;MODE=PostgreSQL
    url: jdbc:mysql://localhost:3306/algo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none # disable DB schema creation from entity

  flyway:
    enabled: false
    baseline-on-migrate: true



